### ISSUE TITLE
[Bug]: java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hbase.KeyValue

### ISSUE THREAD

**Issue by leilinen** [oceanbase/flink-connector-oceanbase#71]
### Describe the bug

 when flink job is running, write records flush into obkv, the job throw a exception, the fully stack below
 ```
 [12] -> Sink: Writer (3/12)#8 (70d3a46a4f73a2acf35c40124d04b158_c0cf586e070e56aca9ca18abfa4fa59d_2_8) switched from RUNNING to FAILED with failure cause:
java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hbase.KeyValue
	at org.apache.hadoop.hbase.client.Put.createPutKeyValue(Put.java:177) ~[hbase-0.94.27.jar:0.94.27]
	at org.apache.hadoop.hbase.client.Put.add(Put.java:142) ~[hbase-0.94.27.jar:0.94.27]
	at org.apache.hadoop.hbase.client.Put.add(Put.java:128) ~[hbase-0.94.27.jar:0.94.27]
	at com.oceanbase.connector.flink.sink.OBKVHBaseRecordFlusher.lambda$flush$1(OBKVHBaseRecordFlusher.java:85) ~[flink-connector-obkv-hbase-1.2.jar:1.2]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_281]
	at com.oceanbase.connector.flink.sink.OBKVHBaseRecordFlusher.flush(OBKVHBaseRecordFlusher.java:83) ~[flink-connector-obkv-hbase-1.2.jar:1.2]
	at com.oceanbase.connector.flink.sink.OceanBaseWriter.flush(OceanBaseWriter.java:198) ~[flink-connector-oceanbase-base-1.2.jar:1.2]
	at org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.prepareSnapshotPreBarrier(SinkWriterOperator.java:168) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.prepareSnapshotPreBarrier(RegularOperatorChain.java:89) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.checkpointState(SubtaskCheckpointCoordinatorImpl.java:322) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$performCheckpoint$15(StreamTask.java:1318) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.runThrowing(StreamTaskActionExecutor.java:50) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.performCheckpoint(StreamTask.java:1306) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.triggerCheckpointOnBarrier(StreamTask.java:1263) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.io.checkpointing.CheckpointBarrierHandler.notifyCheckpoint(CheckpointBarrierHandler.java:147) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.triggerCheckpoint(SingleCheckpointBarrierHandler.java:287) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.access$100(SingleCheckpointBarrierHandler.java:64) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler$ControllerImpl.triggerGlobalCheckpoint(SingleCheckpointBarrierHandler.java:488) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.io.checkpointing.AbstractAlignedBarrierHandlerState.triggerGlobalCheckpoint(AbstractAlignedBarrierHandlerState.java:74) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.io.checkpointing.AbstractAlignedBarrierHandlerState.barrierReceived(AbstractAlignedBarrierHandlerState.java:66) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.lambda$processBarrier$2(SingleCheckpointBarrierHandler.java:234) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.markCheckpointAlignedAndTransformState(SingleCheckpointBarrierHandler.java:262) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.processBarrier(SingleCheckpointBarrierHandler.java:231) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.io.checkpointing.CheckpointedInputGate.handleEvent(CheckpointedInputGate.java:181) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.io.checkpointing.CheckpointedInputGate.pollNext(CheckpointedInputGate.java:159) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.emitNext(AbstractStreamTaskNetworkInput.java:118) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:562) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:231) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:858) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:807) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:953) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:932) [flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:746) [flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:562) [flink-dist-1.18.1.jar:1.18.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]
	Suppressed: java.lang.Exception: java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hbase.KeyValue
		at org.apache.flink.util.IOUtils.closeAll(IOUtils.java:262) ~[bigdata-etl-index-flink-1.18.jar:3.34.0]
		at org.apache.flink.core.fs.AutoCloseableRegistry.doClose(AutoCloseableRegistry.java:72) ~[bigdata-etl-index-flink-1.18.jar:3.34.0]
		at org.apache.flink.util.AbstractAutoCloseableRegistry.close(AbstractAutoCloseableRegistry.java:127) ~[bigdata-etl-index-flink-1.18.jar:3.34.0]
		at org.apache.flink.streaming.runtime.tasks.StreamTask.cleanUp(StreamTask.java:970) ~[flink-dist-1.18.1.jar:1.18.1]
		at org.apache.flink.runtime.taskmanager.Task.lambda$restoreAndInvoke$0(Task.java:935) ~[flink-dist-1.18.1.jar:1.18.1]
		at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:953) ~[flink-dist-1.18.1.jar:1.18.1]
		at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:935) [flink-dist-1.18.1.jar:1.18.1]
		at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:746) [flink-dist-1.18.1.jar:1.18.1]
		at org.apache.flink.runtime.taskmanager.Task.run(Task.java:562) [flink-dist-1.18.1.jar:1.18.1]
		at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]
	Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hbase.KeyValue
		at org.apache.hadoop.hbase.client.Put.createPutKeyValue(Put.java:177) ~[hbase-0.94.27.jar:0.94.27]
		at org.apache.hadoop.hbase.client.Put.add(Put.java:142) ~[hbase-0.94.27.jar:0.94.27]
		at org.apache.hadoop.hbase.client.Put.add(Put.java:128) ~[hbase-0.94.27.jar:0.94.27]
		at com.oceanbase.connector.flink.sink.OBKVHBaseRecordFlusher.lambda$flush$1(OBKVHBaseRecordFlusher.java:85) ~[flink-connector-obkv-hbase-1.2.jar:1.2]
		at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_281]
		at com.oceanbase.connector.flink.sink.OBKVHBaseRecordFlusher.flush(OBKVHBaseRecordFlusher.java:83) ~[flink-connector-obkv-hbase-1.2.jar:1.2]
		at com.oceanbase.connector.flink.sink.OceanBaseWriter.flush(OceanBaseWriter.java:198) ~[flink-connector-oceanbase-base-1.2.jar:1.2]
		at com.oceanbase.connector.flink.sink.OceanBaseWriter.close(OceanBaseWriter.java:248) ~[flink-connector-oceanbase-base-1.2.jar:1.2]
		at org.apache.flink.util.IOUtils.closeAll(IOUtils.java:255) ~[bigdata-etl-index-flink-1.18.jar:3.34.0]
		at org.apache.flink.util.IOUtils.closeAll(IOUtils.java:234) ~[bigdata-etl-index-flink-1.18.jar:3.34.0]
		at org.apache.flink.util.IOUtils.closeAll(IOUtils.java:223) ~[bigdata-etl-index-flink-1.18.jar:3.34.0]
		at org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.close(SinkWriterOperator.java:219) ~[flink-dist-1.18.1.jar:1.18.1]
		at org.apache.flink.streaming.runtime.tasks.StreamOperatorWrapper.close(StreamOperatorWrapper.java:163) ~[flink-dist-1.18.1.jar:1.18.1]
		at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.closeAllOperators(RegularOperatorChain.java:125) ~[flink-dist-1.18.1.jar:1.18.1]
		at org.apache.flink.streaming.runtime.tasks.StreamTask.closeAllOperators(StreamTask.java:1062) ~[flink-dist-1.18.1.jar:1.18.1]
		at org.apache.flink.util.IOUtils.closeAll(IOUtils.java:255) ~[bigdata-etl-index-flink-1.18.jar:3.34.0]
		... 9 more
```

### Environment

Flink 1.18.1
OBSERVER 421 bp7 hotfix1 (CE)

### Fast reproduce steps
0. put `flink-connector-obkv-hbase-1.2.jar`, `flink-connector-oceanbase-base-1.2.jar`, `hbase-0.94.27.jar` into {flink_home}/lib
1. submit a flink job, kafka -> window -> obkv
2. when flush records into db, the job throw the exception

**Comment by whhe** [comment]
Please use [flink-sql-connector-obkv-hbase-1.2.jar](https://repo1.maven.org/maven2/com/oceanbase/flink-sql-connector-obkv-hbase/1.2/flink-sql-connector-obkv-hbase-1.2.jar) in Flink SQL job, it's a fat jar which contains all necessary dependencies.

**Comment by leilinen** [comment]
Thanks for your response. With the new connector file, the job running well and never throw the exception.
